### ISSUE TITLE
Full integration of statuses and stages between the apss

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-workspace#78]
send and receive messages with actions which can modify the status and changes of a patient, consent, trial

**Comment by anastath** [comment]
Please take into consideration the Trial statuses described by Despina-ONORACH (points 1 and 2 may be ommitted since we regard the IRB approval ready)

1. In Set-up / In preparation (Not submitted to any IRB)
2. In approval stage (Submitted to IRB – approval(s) pending) 
3. Approved, Not yet recruiting 
4. Recruiting 
5. Enrolling by invitation _ Means that participants are being (or will be) selected from a predetermined 
6. Active, not recruiting (Means that the study is continuing, meaning participants are receiving an intervention or being examined, but new participants are not currently being recruited or enrolled)
7. Suspended 
8. Terminated  
9. Completed
10. Withdrawn

To be elaborated with explanations of each bullet point (a relevant document will be provided by Celine)
